### ISSUE TITLE
Images of chess pieces aren't showing up

### ISSUE THREAD

**Issue by llihcchill** [llihcchill/chessy#1]

**Comment by NinfarZ** [comment]
Hi there! How are the chess pieces supposed to show up on the board? Lined up on each side of the board like this?

![chess](https://user-images.githubusercontent.com/65355075/225324783-fd27d953-4f2b-41af-b87a-09b9416d762e.png)

**Comment by llihcchill** [comment]
sorry for the late reply, thank you so much but I think I'll have them set up without those thingies, and I have fixed the problem (just gotta upload the code which will be sometime tomorrow), though would love some help with making the web app look good with bootstrap!!! thank you again!
